server:
  port: 8084
spring:
  kafka:
    # kafka服务地址
    bootstrap-servers: 127.0.0.1:9092
    producer:
      # 重试次数
      retries: 3
      batch-size: 65536
      buffer-memory: 524288
      # 设置key的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      group-id: 0
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: MANUAL_IMMEDIATE
        # RECORD：当每一条记录被消费者监听器（ListenerConsumer）处理之后提交
        # BATCH：当每一批poll()的数据被消费者监听器（ListenerConsumer）处理之后提交
        # TIME：当每一批poll()的数据被消费者监听器（ListenerConsumer）处理之后，距离上次提交时间大于TIME时提交
        # COUNT：当每一批poll()的数据被消费者监听器（ListenerConsumer）处理之后，被处理record数量大于等于COUNT时提交
        # COUNT_TIME： TIME|COUNT　有一个条件满足时提交
        # MANUAL：当每一批poll()的数据被消费者监听器（ListenerConsumer）处理之后, 手动调用Acknowledgment.acknowledge()后提交
      # MANUAL_IMMEDIATE：手动调用Acknowledgment.acknowledge()后立即提交，一般使用这种
kafka:
  topic:
    group-id: topicGroupId
    topic-name:
      - topic1
      - topic2
      - topic3